version: "3"
services:
    emby:
        image: emby/embyserver:latest
        container_name: emby
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Sao_Paulo
        volumes:
        - /opt/appconfig/emby:/config
        - /mnt:/mnt
        - /opt/transcodes:/trancodes
        - /etc/localtime:/etc/localtime
        ports:
        - 8096:8096
        restart: unless-stopped
    plex:
        image: plexinc/pms-docker:latest
        container_name: plex
        network_mode: host
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Sao_Paulo
        volumes:
        - /opt/appconfig/plex:/config
        - /mnt:/mnt
        - /opt/transcodes:/trancodes
        - /etc/localtime:/etc/localtime
        - /dev/shm:/ram_transcode
        restart: unless-stopped
    tautulli:
        image: linuxserver/tautulli:latest
        container_name: tautulli
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Sao_Paulo
        volumes:
        - /opt/appconfig/tautulli:/config
        - /opt/appconfig/logs/tautulli:/logs
        ports:
        - 8181:8181
        restart: unless-stopped